In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[3, 5], [8, 12]])
matrix

tensor([[ 3,  5],
        [ 8, 12]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 8, 12])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
tensor = torch.tensor([[[1, 2, 3], [2, 4, 6], [3, 6, 9]]])
tensor

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

### Random Tensors

In [18]:
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.3867, 0.1462, 0.7291, 0.3604, 0.5271],
        [0.5791, 0.9289, 0.4095, 0.9095, 0.0162],
        [0.5022, 0.6933, 0.1900, 0.7519, 0.7963]])

In [19]:
random_image_size_tensor = torch.rand(size=(2, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([2, 224, 224]), 3)

### Zeros & Ones

In [20]:
zeros = torch.zeros(size=(3, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### A Range of Tensors & Tensors-Like

In [24]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])