In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[3, 5], [8, 12]])
matrix

tensor([[ 3,  5],
        [ 8, 12]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 8, 12])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
tensor = torch.tensor([[[1, 2, 3], [2, 4, 6], [3, 6, 9]]])
tensor

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

### Random Tensors

In [18]:
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.3867, 0.1462, 0.7291, 0.3604, 0.5271],
        [0.5791, 0.9289, 0.4095, 0.9095, 0.0162],
        [0.5022, 0.6933, 0.1900, 0.7519, 0.7963]])

In [19]:
random_image_size_tensor = torch.rand(size=(2, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([2, 224, 224]), 3)

### Zeros & Ones

In [20]:
zeros = torch.zeros(size=(3, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### A Range of Tensors & Tensors-Like

In [24]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [26]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
# torch.float32
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [37]:
# torch.float32
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Tensor Attributes

In [38]:
print(random_tensor)
print(f"Datatype of Tensor: {random_tensor.dtype}")
print(f"Shape of Tensor: {random_tensor.shape}")
print(f"Device Tensor is on: {random_tensor.device}")

tensor([[0.3867, 0.1462, 0.7291, 0.3604, 0.5271],
        [0.5791, 0.9289, 0.4095, 0.9095, 0.0162],
        [0.5022, 0.6933, 0.1900, 0.7519, 0.7963]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 5])
Device Tensor is on: cpu


### Tensor Operations (Manipulation)

In [39]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
tensor * 10

tensor([10, 20, 30])

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
tensor - 10

tensor([-9, -8, -7])

In [43]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

In [45]:
# Element-Wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [47]:
tensor

tensor([1, 2, 3])

In [48]:
1 * 1 + 2 * 2 + 3 * 3

14

In [49]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.59 ms, sys: 1.01 ms, total: 2.6 ms
Wall time: 2.44 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 552 µs, sys: 0 ns, total: 552 µs
Wall time: 474 µs


tensor(14)

### Shape Errors

In [55]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 8], [9, 10], [11, 12]])

# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
# torch.matmul(tensor_A, tensor_B)

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [59]:
print(f"Original Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (Same Shape as above), tensor_B = {tensor_B.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- Inner Dimensions must Match")
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output Shape: {output.shape}")

Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (Same Shape as above), tensor_B = torch.Size([3, 2])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner Dimensions must Match
Output:
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output Shape: torch.Size([3, 3])


### Tensor Aggregation