In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[3, 5], [8, 12]])
matrix

tensor([[ 3,  5],
        [ 8, 12]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 8, 12])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
tensor = torch.tensor([[[1, 2, 3], [2, 4, 6], [3, 6, 9]]])
tensor

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])